const trans = {
    en: {
        RECIPES: "Recipes",
        FOLLOWERS: "Followers",
        FOLLOWING: "Following",
        BIRTHDATE: "BirthDate",
        DATE_PICKED: "Date Picked",
        TIME_PICKED: "Time Picked",
        EVENT_NAME: "Event Name",
        OCCASION: "Occasion",
        HOW_MANY_GUESTS: "How many guests?",
        FREE_TEXT: "Free Text",
        SET_ALARM: "Set Alarm",
        SAVE: "Save",
        UPDATE: "Update",
        CREATE_SHOP_LIST: "Create Shop List",
        FROM_DATE: "From Date",
        TO_DATE: "To Date",
        ADD_NEW_EVENT: "Add new Event",
        NAME: "Name",
        SURNAME: "Surname",
        USER_NAME: "User Name",
        GENDER: "Gender",
        EMAIL: "E-mail",
        ADDRESS: "Address",
        NUM: "num",
        COUNTRY: "Country",
        ZIP: "ZIP",
        PHONE_NUMBER: "Phone Num.",
        PROFESSION: "Profession",
        SKILLS: "Skills",
        DIET: "Diet",
        FAVORITE_FOOD: "Favorite Food",
        FAVORITE_RESTAURANTS: "Favorite Restaurants",
        MEAL_PREFERENCES: "Meal Preferences",
        FOOD_INTERESTS: "Food Interests",
        ABOUT_ME: "About me",
        FREE_TEXT_MAX: 'Free Text max 256 char.',
        INSTAGRAM: "Instagram",
        TIKTOK: "TikTok",
        FACEBOOK: "Facebook",
        PINTEREST: "Pinterest",
        BLOG: "Blog",
        GLOBAL_STATUS: "Global Status",
        SAVE_PROFILE: "Save Profile",
        MY_MAILS: "My Mails",
        COMPOSE: "Compose",
        FROM: "From",
        SUBJECT: "Subject:",
        DATE: "Date",
        TO: "To",
        MESSAGE: "Message:",
        CLEAR_MAIL: "Clear Mail",
        SEND_MAIL: "Send Mail",
        CLOSE_MAIL: "Close Mail",
        UNITS_CONVERTOR: "Units Convertor",
        MASS: "Mass",
        VOLUME: "Volume",
        TEMPERATURE: "Temperature",
        MAIL_SENT: "Mail sent",
        CONTACT_US: "Constact Us",
        PLEASE_CONTACT_US: "Please Contact Us for any reason at all!!!",
        WE_ARE_HERE: "We are here for You!!!",
        TITLE: "Title",
        MY_FRIENDS: "My Friends",
        MY_SHOP_LIST: "My Shop Lists",
        MY_MEALS: "My Meals",
        CREATE_A_MEAL: "Create a Meal",
        CANCEL: "Cancel",
        DELETE: "Delete",
        ARE_YOU_SURE: "Are you sure???",
        PERMANTLY_DELETING: "You are permantly deleting this meal from your meals!!!",
        SAVE_SHOP_LIST: 'Save Shop List!',
        DELETE_SHOP_LIST: "Delete Shop List!",
        BACK_HOME: "Back Home!",
        SUBMIT: "Submit",
        ENTER: "Enter",
        SHOP_LIST_NAME: "Shop List Name",
        YOUR_SHOP_PROGRESS: "your shop progress",
        YES: "Yes",
        NO: "No",
        MORE: "more",
        LESS: "less",
        FOLLOW: "Follow",
        SEARCH_FOR: "Search for...",
        FOOD_COURSES: "Food Courses",
        FOOD_COURSE: "Food Course",
        HOW_TO_SEARCH: "How to search?",
        SEARCH_MSG:
            `\nby_  -> user search\n\ntag_  -> tag search\n\nrecipe_  -> recipe search\n\nmeal_  -> meal search\n\nevent_  -> event search`,
        ADD: "ADD",
        UPDATE_RECIPE: "Update Recipe",
        NEW_RECIPE: "New Recipe",
        ADD_A_IMAGE: "Add an image!",
        PREP_TIME: "Prep.Time",
        MIN: "min",
        COOK_TIME: "Cook Time",
        DIFFICULTY: "Difficulty",
        DIF: "Dif",
        SERVES: "Serves",
        PPL: "ppl.",
        SDIET: "S.Diet",
        COURSE: "Course",
        OK: "OK",
        HASHTAG: "HashTag",
        HASHTAG_INFO: 'Just press "space" or "," to enter your HashTag, \nNo need for #. \nMaximum 20 Characters.\nTo delete one just click on it.',
        ENTER_YOUR_TAGS: "Enter your tags!",
        INGREDIENTS: "Ingredients",
        OPEN_UNITS_CONVERTOR: "Open Units Convertor",
        QTY: "qty",
        RECIPE_NAME: "Recipe Name",
        SPECIAL_DIET: "Special Diet",
        UN: "Un.",
        SEARCH: "Search...",
        PREPARATION: "Preparation",
        PREPARATION_STEP: 'Preparation Step',
        STEP: "Step",
        PUBLIC: "Public",
        PRIVATE: "Private",
        CLEAR_FORM: "Clear Form",
        ADD_RECIPE_TO_MY_BOOK: "Add Recipe to My Book",
        NO_RESULT: 'No Result!!!',
        HOME: "Home",
        MY_PROFILE: "My Profile",
        MY_SETTINGS: "My Settings",
        MY_CALENDAR: "My Calendar",
        DONATE_A_MEAL: "Donate a Meal",
        TELL_YOUR_FRIENS: "Tell Your Friends",
        LOG_OUT: "Log Out",
        HELP: "Help",
        VALIDATION: 'Validation',
        DIETARY_RESTRICTIONS: "Dietary Restrictions",
        COOKING_SKILLS: "Cooking Skills",
        COUNTRY_CODE: "Country Code",
        GENDER: "Gender",
        DONT_FORGET: `Don't forget to read your e-mails!!!`,
        EMAIL_WILL_DEL: `E-mails will be automatically deleted after 30 days.`,
        PLEASE_ADD_THE_RECIPIENT: 'Please add the recipient!!!',
        CELSIUS: "Celsius",
        FAHRENHEIT: "Fahrenheit",
        OVEN_LEVEL: "Oven Level",
        EVENT_PERMANET_DELETE: 'You are permantly deleting this event from your calendar!!!',
        MEAL_NAME: "Meal Name",
        STOP_FOLLOWING: "Stop Following",
        START_FOLLOWING: "Start Following",
    },
    pt: {

    },
    sp: {

    },
    fr: {

    },
    he: {

    },

}

export default trans